version: '3.9'

networks:
  traefik-net:
    external: true

services:

  apiserver:
    image: hamband_volunteer_api
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.volunteer-api.rule=Host(`hamband.math.sharif.edu`) && PathPrefix(`/volunteer/api`)"
        - "traefik.http.routers.volunteer-api.entrypoints=web-secure"
        - "traefik.http.routers.volunteer-api.tls=true"
        - "traefik.http.routers.volunteer-api.tls.certresolver=myresolver"
        - "traefik.http.services.to-volunteer-api.loadbalancer.server.port=80"
    networks:
      - traefik-net
    volumes:
      - ./sqlite:/sqlite
    environment:
      - DB=sqlite:///sqlite/main.db
      - PATH_PREFIX=/volunteer/api/v1
      - API_KEYS=
      - SHOW_DOCS=1
      - NO_HTTP=1